/**
 * @file
 *
 * Reading `tests/data/tar/manifest.tsv`: what the reference says each fixture
 * contains.
 *
 * The manifest is generated by `tools/oracle/make_corpus.py` inside the pinned
 * container, from Python's `tarfile` reading each archive back. **It is the
 * reference's opinion, not this library's**, which is the only reason a test
 * comparing against it means anything: an expectation read off the
 * implementation under test pins whatever that implementation happens to do.
 *
 * Copyright 2026 by Corey Pennycuff
 */

#ifndef GHOTI_IO_GARC_TEST_TAR_MANIFEST_H
#define GHOTI_IO_GARC_TEST_TAR_MANIFEST_H

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

namespace garctest {

/** One row of the manifest: one member, as the reference read it. */
struct ManifestRow {
  std::string archive;
  size_t index = 0;
  std::string name;
  std::string type;
  uint64_t size = 0;
  int64_t mtime = 0;
  uint32_t mtime_nanoseconds = 0;
  uint32_t mode = 0;
  int64_t uid = 0;
  int64_t gid = 0;
  std::string uname;
  std::string gname;
  std::string link;
};

/**
 * Undo the manifest's escaping.
 *
 * A member name is bytes and can hold a tab, a newline or a NUL, any of which
 * would end a field or a line early in a tab-separated file - so the generator
 * escapes everything outside printable ASCII as `\xHH`, and a backslash as
 * `\\`. Decoding here rather than comparing escaped forms means the test
 * compares the bytes the library reports against the bytes the reference
 * reported, which is the comparison that matters.
 */
inline std::string manifest_unescape(const std::string & field) {
  std::string out;
  for (size_t i = 0; i < field.size();) {
    if (field[i] != '\\') {
      out.push_back(field[i]);
      ++i;
      continue;
    }
    if (i + 1 < field.size() && field[i + 1] == '\\') {
      out.push_back('\\');
      i += 2;
      continue;
    }
    if (i + 3 < field.size() && field[i + 1] == 'x') {
      const std::string hex = field.substr(i + 2, 2);
      out.push_back(static_cast<char>(std::strtoul(hex.c_str(), nullptr, 16)));
      i += 4;
      continue;
    }
    // A lone backslash the generator did not write. Kept rather than dropped,
    // so that a malformed manifest shows up as a comparison failure naming the
    // bytes instead of silently becoming a shorter name.
    out.push_back('\\');
    ++i;
  }
  return out;
}

/**
 * Every row of the manifest, grouped by archive and in file order.
 *
 * Returns an empty map when the manifest is missing, which the tests treat as a
 * failure rather than a skip: the corpus is committed, so its absence is a
 * broken checkout and not an optional reference.
 */
inline std::map<std::string, std::vector<ManifestRow>> manifest_load(
    const std::string & path) {
  std::map<std::string, std::vector<ManifestRow>> rows;
  std::ifstream input(path);
  if (!input) {
    return rows;
  }

  std::string line;
  while (std::getline(input, line)) {
    if (line.empty() || line[0] == '#') {
      continue;
    }
    std::vector<std::string> fields;
    std::string field;
    std::istringstream split(line);
    while (std::getline(split, field, '\t')) {
      fields.push_back(field);
    }
    // Trailing empty fields are dropped by getline when the line ends with a
    // tab, and the last three fields are routinely empty - so a short row is
    // padded rather than rejected.
    while (fields.size() < 13) {
      fields.push_back("");
    }

    ManifestRow row;
    row.archive = fields[0];
    row.index = std::strtoul(fields[1].c_str(), nullptr, 10);
    row.name = manifest_unescape(fields[2]);
    row.type = fields[3];
    row.size = std::strtoull(fields[4].c_str(), nullptr, 10);
    row.mtime = std::strtoll(fields[5].c_str(), nullptr, 10);
    // The sub-second part, which only a pax `mtime=` record carries. It is a
    // column of its own because the reference's own mtime is a float and cannot
    // hold a nanosecond - see member_time() in the generator.
    row.mtime_nanoseconds
        = static_cast<uint32_t>(std::strtoul(fields[6].c_str(), nullptr, 10));
    // Octal, with the leading 0 the generator writes.
    row.mode = static_cast<uint32_t>(std::strtoul(fields[7].c_str(), nullptr, 8));
    row.uid = std::strtoll(fields[8].c_str(), nullptr, 10);
    row.gid = std::strtoll(fields[9].c_str(), nullptr, 10);
    row.uname = manifest_unescape(fields[10]);
    row.gname = manifest_unescape(fields[11]);
    row.link = manifest_unescape(fields[12]);
    rows[row.archive].push_back(row);
  }
  return rows;
}

/**
 * Member names as bsdtar lists them, grouped by archive and in file order.
 *
 * **A separate file from the manifest, because the two references disagree about
 * one thing and each is right about its own half.** Python's `tarfile` strips a
 * directory member's trailing slash - the header says `sizes/` and it reports
 * `sizes` - where bsdtar and GNU tar both keep it. This library reports what the
 * container said, so it agrees with those two; comparing names against the one
 * that normalises would need either a wrong expectation or a tolerance wide
 * enough to hide a real truncation. So bsdtar answers about names and tarfile
 * about everything it does not normalise.
 */
inline std::map<std::string, std::vector<std::string>> names_load(
    const std::string & path) {
  std::map<std::string, std::vector<std::string>> rows;
  std::ifstream input(path);
  if (!input) {
    return rows;
  }
  std::string line;
  while (std::getline(input, line)) {
    if (line.empty() || line[0] == '#') {
      continue;
    }
    std::vector<std::string> fields;
    std::string field;
    std::istringstream split(line);
    while (std::getline(split, field, '\t')) {
      fields.push_back(field);
    }
    if (fields.size() < 3) {
      fields.resize(3);
    }
    rows[fields[0]].push_back(manifest_unescape(fields[2]));
  }
  return rows;
}

/**
 * One row of `verdicts.tsv`: what each reference would *do* with a name.
 *
 * The only part of the corpus that records a decision rather than a reading, and
 * the only outside opinion ::garc_name_check() has to be measured against. See
 * verdicts() in the generator for what the columns mean and why there are three.
 */
struct VerdictRow {
  std::string archive;
  size_t index = 0;
  std::string name;
  /** `tarfile.data_filter`: "same", "rewrite", or an exception's name. */
  std::string python_data;
  /** `tarfile.tar_filter`, the permissive policy, as the control. */
  std::string python_tar;
  /** "refused" or "extracted", from `bsdtar -x` actually running. */
  std::string libarchive;

  /** Whether Python's data filter would not leave this name alone. */
  bool python_acts() const {
    return python_data != "same";
  }
  /** Whether libarchive refused the member outright. */
  bool libarchive_refused() const {
    return libarchive == "refused";
  }
};

/**
 * Every verdict row, in file order.
 *
 * A flat vector rather than a map by archive: the cross-check walks all of them
 * and the archive is a column, so grouping would only have to be undone.
 */
inline std::vector<VerdictRow> verdicts_load(const std::string & path) {
  std::vector<VerdictRow> rows;
  std::ifstream input(path);
  if (!input) {
    return rows;
  }
  std::string line;
  while (std::getline(input, line)) {
    if (line.empty() || line[0] == '#') {
      continue;
    }
    std::vector<std::string> fields;
    std::string field;
    std::istringstream split(line);
    while (std::getline(split, field, '\t')) {
      fields.push_back(field);
    }
    if (fields.size() < 6) {
      fields.resize(6);
    }
    VerdictRow row;
    row.archive = fields[0];
    row.index = std::strtoul(fields[1].c_str(), nullptr, 10);
    row.name = manifest_unescape(fields[2]);
    row.python_data = fields[3];
    row.python_tar = fields[4];
    row.libarchive = fields[5];
    rows.push_back(row);
  }
  return rows;
}

/** Read a whole fixture into memory. Empty on failure. */
inline std::vector<uint8_t> read_fixture(const std::string & path) {
  std::ifstream input(path, std::ios::binary);
  if (!input) {
    return {};
  }
  return std::vector<uint8_t>(std::istreambuf_iterator<char>(input),
      std::istreambuf_iterator<char>());
}

} // namespace garctest

#endif // GHOTI_IO_GARC_TEST_TAR_MANIFEST_H
