/**
 * @file
 *
 * Building tar headers by hand, for the cases no reference writes.
 *
 * **Every fixture that a real tar tool can produce is generated by one**, in the
 * pinned container, because a hand-built corpus contains the shapes whoever
 * wrote it thought of. What is here is the complement of that: headers no
 * current writer emits, so there is nothing to generate them with.
 *
 * Three kinds, and each is here for a reason the generated corpus cannot cover:
 *
 *   - **A signed header checksum.** Writers that summed the header's bytes as
 *     signed chars are decades gone, and the reader accepts them because
 *     refusing rejects real old archives. Nothing in the container writes one,
 *     so the only way to put the accepting branch in a position to fail is to
 *     build one.
 *   - **Damage.** A bad checksum, a truncated archive, a member that declares
 *     more bytes than it has. GNU tar will not write these on request.
 *   - **Fields at their limits.** A base-256 size, an octal field with no
 *     terminator, a blank field. Some are reachable through a real writer with
 *     enough effort and all are cheaper and clearer built directly.
 *
 * Anything built here is labelled as hand-built where it is used, so that a
 * reader can tell an assertion about the format from an assertion about what
 * this file happens to construct.
 *
 * Copyright 2026 by Corey Pennycuff
 */

#ifndef GHOTI_IO_GARC_TEST_TAR_BUILDER_H
#define GHOTI_IO_GARC_TEST_TAR_BUILDER_H

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

namespace garctest {

/** One tar block. */
constexpr size_t kTarBlock = 512;

/** A header under construction: 512 bytes, NUL-filled. */
struct TarHeader {
  std::vector<uint8_t> bytes = std::vector<uint8_t>(kTarBlock, 0);

  /** Write a NUL-padded string at an offset, truncating at the field width. */
  void field(size_t offset, size_t width, const std::string & text) {
    const size_t take = text.size() < width ? text.size() : width;
    std::memcpy(bytes.data() + offset, text.data(), take);
  }

  /**
   * Write an octal number the way tar does: right-aligned, zero-padded, with a
   * NUL in the last byte.
   *
   * That is one of four spellings a real field may use - the others are a space
   * terminator, both, and neither - and the reader has to accept all of them, so
   * the other three are written by `octal_raw` in the tests that need them.
   */
  void octal(size_t offset, size_t width, uint64_t value) {
    std::string text(width - 1, '0');
    for (size_t i = width - 1; i-- > 0;) {
      text[i] = static_cast<char>('0' + (value & 7u));
      value >>= 3;
    }
    std::memcpy(bytes.data() + offset, text.data(), width - 1);
    bytes[offset + width - 1] = 0;
  }

  /** Write raw bytes, for a field spelling `octal()` does not produce. */
  void raw(size_t offset, const std::vector<uint8_t> & data) {
    std::memcpy(bytes.data() + offset, data.data(), data.size());
  }

  /**
   * Write base-256, GNU's extension for a value an octal field cannot hold.
   *
   * Bit 7 of the first byte is the flag and bit 6 is the sign, so the value is
   * 7 + 8*(width-1) bits wide. Written here the way GNU writes it: the flag set
   * and the magnitude right-aligned.
   */
  void base256(size_t offset, size_t width, uint64_t value) {
    for (size_t i = width; i-- > 0;) {
      bytes[offset + i] = static_cast<uint8_t>(value & 0xFFu);
      value >>= 8;
    }
    bytes[offset] = static_cast<uint8_t>(bytes[offset] | 0x80u);
  }

  /** Fill in the ustar magic and version. */
  void ustar() {
    static const uint8_t magic[8]
        = {'u', 's', 't', 'a', 'r', 0, '0', '0'};
    std::memcpy(bytes.data() + 257, magic, sizeof(magic));
  }

  /** Fill in GNU's magic, which runs the two fields together. */
  void gnu() {
    static const uint8_t magic[8]
        = {'u', 's', 't', 'a', 'r', ' ', ' ', 0};
    std::memcpy(bytes.data() + 257, magic, sizeof(magic));
  }

  /**
   * Compute and write the checksum.
   *
   * @param as_signed Sum the bytes as signed chars, which is what the writers
   *   this reader still accepts did. The two sums differ only when a header
   *   holds a byte above 0x7F, which is why a caller wanting to test the signed
   *   branch has to put one there.
   */
  void checksum(bool as_signed = false) {
    std::memset(bytes.data() + 148, ' ', 8);
    long sum = 0;
    for (size_t i = 0; i < kTarBlock; ++i) {
      sum += as_signed ? static_cast<long>(static_cast<int8_t>(bytes[i]))
                       : static_cast<long>(bytes[i]);
    }
    // Six octal digits, NUL, space - which is what every writer produces. The
    // buffer is oversized because a sum cannot exceed 6 octal digits here (512
    // bytes at 255 is 130560, five digits) and the compiler cannot know that.
    char text[32];
    std::snprintf(text, sizeof(text), "%06lo", sum < 0 ? 0L : sum);
    std::memcpy(bytes.data() + 148, text, 6);
    bytes[154] = 0;
    bytes[155] = ' ';
  }
};

/** A minimal ustar file header for a member of `size` bytes. */
inline TarHeader file_header(const std::string & name, uint64_t size,
    uint32_t mode = 0644u, char typeflag = '0') {
  TarHeader header;
  header.field(0, 100, name);
  header.octal(100, 8, mode);
  header.octal(108, 8, 0);
  header.octal(116, 8, 0);
  header.octal(124, 12, size);
  header.octal(136, 12, 0);
  header.bytes[156] = static_cast<uint8_t>(typeflag);
  header.ustar();
  header.checksum();
  return header;
}

/**
 * A GNU `L` or `K` carrier header for a payload of `declared` bytes.
 *
 * The name is `././@LongLink`, which is what GNU writes and what a reader must
 * not report as a member. `declared` is taken rather than derived from the
 * payload, because half the cases here are a declaration that disagrees with the
 * bytes behind it.
 *
 * @param typeflag 'L' for a name, 'K' for a link target.
 * @param declared The size field: GNU writes the string's length plus one, for
 *   the terminator.
 */
inline TarHeader long_header(char typeflag, uint64_t declared) {
  TarHeader header;
  header.field(0, 100, "././@LongLink");
  header.octal(100, 8, 0644u);
  header.octal(108, 8, 0);
  header.octal(116, 8, 0);
  header.octal(124, 12, declared);
  header.octal(136, 12, 0);
  header.bytes[156] = static_cast<uint8_t>(typeflag);
  header.gnu();
  header.checksum();
  return header;
}

/**
 * A pax `x` or `g` carrier header for a record block of `declared` bytes.
 *
 * The name is what GNU tar writes - `./PaxHeaders/<member>` for an `x` and
 * `GlobalHead` for a `g` - and a reader must report neither.
 *
 * @param typeflag 'x' for records that apply to the next member, 'g' for records
 *   that apply until replaced.
 * @param declared The size field. Taken rather than derived, because several
 *   cases here are a declaration that disagrees with the bytes behind it.
 */
inline TarHeader pax_header(char typeflag, uint64_t declared) {
  TarHeader header;
  header.field(0, 100, typeflag == 'g' ? "GlobalHead" : "./PaxHeaders/member");
  header.octal(100, 8, 0644u);
  header.octal(108, 8, 0);
  header.octal(116, 8, 0);
  header.octal(124, 12, declared);
  header.octal(136, 12, 0);
  header.bytes[156] = static_cast<uint8_t>(typeflag);
  header.ustar();
  header.checksum();
  return header;
}

/**
 * One pax record: `len SP key = value LF`.
 *
 * `len` counts itself, which is the one self-referential field in any of these
 * formats - so the width of the number changes the number, and this iterates to a
 * fixed point rather than guessing. A test that hard-coded a length would be
 * asserting against whatever it happened to compute.
 */
inline std::string pax_record(
    const std::string & key, const std::string & value) {
  const size_t body = key.size() + value.size() + 3u; // space, '=', newline
  size_t length = body + 1u;
  for (;;) {
    const size_t digits = std::to_string(length).size();
    if (body + digits == length) {
      break;
    }
    length = body + digits;
  }
  return std::to_string(length) + " " + key + "=" + value + "\n";
}

/** An archive: headers and data blocks, with the end marker appended. */
class TarArchive {
public:
  /** Append a header block. */
  TarArchive & header(const TarHeader & block) {
    bytes_.insert(bytes_.end(), block.bytes.begin(), block.bytes.end());
    return *this;
  }

  /** Append data, padded out to a whole block as tar does. */
  TarArchive & data(const std::string & payload) {
    bytes_.insert(bytes_.end(), payload.begin(), payload.end());
    const size_t remainder = payload.size() % kTarBlock;
    if (remainder) {
      bytes_.insert(bytes_.end(), kTarBlock - remainder, 0);
    }
    return *this;
  }

  /** Append raw bytes, for a deliberately malformed tail. */
  TarArchive & raw(const std::vector<uint8_t> & payload) {
    bytes_.insert(bytes_.end(), payload.begin(), payload.end());
    return *this;
  }

  /** Append `count` zero blocks. Two is the end-of-archive marker. */
  TarArchive & marker(size_t count = 2) {
    bytes_.insert(bytes_.end(), count * kTarBlock, 0);
    return *this;
  }

  const std::vector<uint8_t> & bytes() const { return bytes_; }

private:
  std::vector<uint8_t> bytes_;
};

} // namespace garctest

#endif // GHOTI_IO_GARC_TEST_TAR_BUILDER_H
