/**
 * @file
 *
 * Reading `tests/data/zip/`: what the references say each fixture contains, and
 * what they do when handed one.
 *
 * Three files, because there are three kinds of answer and no one reference gives
 * all of them. `manifest.tsv` is Python's `zipfile` reading every field it
 * reports; `names.tsv` is bsdtar's type, mode and link target, which are
 * *decisions* Python's module does not make; `openings.tsv` is whether each of
 * four references would open the archive at all, which is where the corpus
 * records the three fixtures they disagree about.
 *
 * All of it is generated by `tools/oracle/make_zip_corpus.py` inside the pinned
 * container. **It is the references' opinions, not this library's**, which is the
 * only reason a test comparing against it means anything.
 *
 * Copyright 2026 by Corey Pennycuff
 */

#ifndef GHOTI_IO_GARC_TEST_ZIP_MANIFEST_H
#define GHOTI_IO_GARC_TEST_ZIP_MANIFEST_H

#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include "tar_manifest.h"

namespace garctest {

/** One row of the zip manifest: one member, as Python's zipfile read it. */
struct ZipManifestRow {
  std::string archive;
  size_t index = 0;
  std::string name;
  uint64_t size = 0;
  uint64_t compressed_size = 0;
  uint16_t method = 0;
  uint32_t crc = 0;
  /** The six DOS fields, as `YYYY-MM-DDThh:mm:ss`. */
  std::string dos_datetime;
  uint16_t flags = 0;
  bool utf8 = false;
  /** `(external_attr >> 16) & 0xFFFF`, which is a Unix mode where there is one. */
  uint32_t mode = 0;
  /** `version made by`'s high byte: 3 is Unix. */
  unsigned create_system = 0;
  unsigned version_needed = 0;
  uint64_t header_offset = 0;
  std::string comment;
  /** The extra field's ids and lengths, as `id/len,id/len`. */
  std::string extra_ids;

  /**
   * The total length of the extra field the ids describe.
   *
   * Four bytes of header per field plus its payload. Derived here rather than
   * being a column of its own, because the ids are what the generator can report
   * without decoding a payload - and this is the one number a reader's walk over
   * the block can be checked against.
   */
  size_t extra_length() const {
    size_t total = 0;
    size_t at = 0;
    while (at < extra_ids.size()) {
      const size_t comma = extra_ids.find(',', at);
      const std::string field = extra_ids.substr(at,
          comma == std::string::npos ? std::string::npos : comma - at);
      const size_t slash = field.find('/');
      if (field.size() && field[0] == '+') {
        // A trailing fragment the generator could not parse as a field. It is
        // still part of the block's length.
        total += std::strtoul(field.c_str() + 1, nullptr, 10);
      }
      else if (slash != std::string::npos) {
        total += 4u + std::strtoul(field.c_str() + slash + 1, nullptr, 10);
      }
      if (comma == std::string::npos) {
        break;
      }
      at = comma + 1u;
    }
    return total;
  }

  /**
   * The DOS date and time as seconds since the epoch, read as UTC.
   *
   * **`timegm` on purpose, rather than the library's own conversion.** The point
   * of comparing against this is that two independent implementations of the
   * civil-date arithmetic agree; calling into the library would compare it with
   * itself. `timegm` is not in C17, which is why the library cannot use it - it
   * is in POSIX, and these tests are built for one platform where the library is
   * not.
   */
  int64_t dos_epoch() const {
    std::tm parts;
    std::memset(&parts, 0, sizeof(parts));
    unsigned year = 0, month = 0, day = 0, hour = 0, minute = 0, second = 0;
    if (std::sscanf(dos_datetime.c_str(), "%u-%u-%uT%u:%u:%u", &year, &month,
            &day, &hour, &minute, &second)
        != 6) {
      return 0;
    }
    parts.tm_year = static_cast<int>(year) - 1900;
    parts.tm_mon = static_cast<int>(month) - 1;
    parts.tm_mday = static_cast<int>(day);
    parts.tm_hour = static_cast<int>(hour);
    parts.tm_min = static_cast<int>(minute);
    parts.tm_sec = static_cast<int>(second);
    return static_cast<int64_t>(timegm(&parts));
  }
};

/** Split a tab-separated line, padding to `columns` fields. */
inline std::vector<std::string> zip_split(
    const std::string & line, size_t columns) {
  std::vector<std::string> fields;
  std::string field;
  std::istringstream split(line);
  while (std::getline(split, field, '\t')) {
    fields.push_back(field);
  }
  while (fields.size() < columns) {
    fields.push_back("");
  }
  return fields;
}

/** Every manifest row, grouped by archive and in file order. */
inline std::map<std::string, std::vector<ZipManifestRow>> zip_manifest_load(
    const std::string & path) {
  std::map<std::string, std::vector<ZipManifestRow>> rows;
  std::ifstream input(path);
  if (!input) {
    return rows;
  }
  std::string line;
  while (std::getline(input, line)) {
    if (line.empty() || line[0] == '#') {
      continue;
    }
    const std::vector<std::string> fields = zip_split(line, 16);
    ZipManifestRow row;
    row.archive = fields[0];
    row.index = std::strtoul(fields[1].c_str(), nullptr, 10);
    row.name = manifest_unescape(fields[2]);
    row.size = std::strtoull(fields[3].c_str(), nullptr, 10);
    row.compressed_size = std::strtoull(fields[4].c_str(), nullptr, 10);
    row.method = static_cast<uint16_t>(std::strtoul(fields[5].c_str(), nullptr, 10));
    row.crc = static_cast<uint32_t>(std::strtoul(fields[6].c_str(), nullptr, 16));
    row.dos_datetime = fields[7];
    row.flags = static_cast<uint16_t>(std::strtoul(fields[8].c_str(), nullptr, 16));
    row.utf8 = fields[9] == "1";
    // Octal, with the leading 0 the generator writes.
    row.mode = static_cast<uint32_t>(std::strtoul(fields[10].c_str(), nullptr, 8));
    row.create_system = std::strtoul(fields[11].c_str(), nullptr, 10);
    row.version_needed = std::strtoul(fields[12].c_str(), nullptr, 10);
    row.header_offset = std::strtoull(fields[13].c_str(), nullptr, 10);
    row.comment = manifest_unescape(fields[14]);
    row.extra_ids = fields[15];
    rows[row.archive].push_back(row);
  }
  return rows;
}

/** One row of `names.tsv`: what bsdtar decided a member is. */
struct ZipNameRow {
  std::string archive;
  size_t index = 0;
  /** "file", "directory", "symlink" or "other". */
  std::string type;
  /** libarchive's rendering of the mode, e.g. `-rw-r--r--`. */
  std::string mode;
  std::string name;
  std::string link;
};

/** Every names.tsv row, grouped by archive and in file order. */
inline std::map<std::string, std::vector<ZipNameRow>> zip_names_load(
    const std::string & path) {
  std::map<std::string, std::vector<ZipNameRow>> rows;
  std::ifstream input(path);
  if (!input) {
    return rows;
  }
  std::string line;
  while (std::getline(input, line)) {
    if (line.empty() || line[0] == '#') {
      continue;
    }
    const std::vector<std::string> fields = zip_split(line, 6);
    ZipNameRow row;
    row.archive = fields[0];
    row.index = std::strtoul(fields[1].c_str(), nullptr, 10);
    row.type = fields[2];
    row.mode = manifest_unescape(fields[3]);
    row.name = manifest_unescape(fields[4]);
    row.link = manifest_unescape(fields[5]);
    rows[row.archive].push_back(row);
  }
  return rows;
}

/** One row of `openings.tsv`: whether a reference would open an archive. */
struct ZipOpeningRow {
  std::string archive;
  std::string reference;
  /** "accepted" or "refused". */
  std::string verdict;
  /** The exit status, or "-" for the in-process reference. */
  std::string status;
  std::string note;

  bool refused() const {
    return verdict == "refused";
  }
};

/** Every openings.tsv row, in file order. */
inline std::vector<ZipOpeningRow> zip_openings_load(const std::string & path) {
  std::vector<ZipOpeningRow> rows;
  std::ifstream input(path);
  if (!input) {
    return rows;
  }
  std::string line;
  while (std::getline(input, line)) {
    if (line.empty() || line[0] == '#') {
      continue;
    }
    const std::vector<std::string> fields = zip_split(line, 5);
    ZipOpeningRow row;
    row.archive = fields[0];
    row.reference = fields[1];
    row.verdict = fields[2];
    row.status = fields[3];
    row.note = manifest_unescape(fields[4]);
    rows.push_back(row);
  }
  return rows;
}

} // namespace garctest

#endif // GHOTI_IO_GARC_TEST_ZIP_MANIFEST_H
